[package]
name = "dxlib-ffi"
version = "0.1.0"
edition = "2024"
build = "build.rs"
[dependencies]
anyhow = "1.0.98"
dxlib-ffi-macro = {path = "./dxlib-ffi-macro"}

[workspace]
members = [
    "dxlib-ffi-macro"
]
